djangogramm/urls.py
from django.contrib.admin import site
from django.urls import path, include
from djangogramm.settings import DEBUG


urlpatterns = [
    path('admin/', site.urls),
    path('', include('feed.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls'))
]

if DEBUG:
    urlpatterns = [path("__debug__/", include("debug_toolbar.urls"))] + urlpatterns

feed/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from feed.views import Feed, Profile, CreatePost, Like, Follow, AWSLambdaWebhook

urlpatterns = [
    path('', Feed.as_view(), name="feed"),
    path('profile/<int:user_id>', login_required(Profile.as_view()), name="profile"),
    path('create_post/', login_required(CreatePost.as_view()), name="create_post"),
    path('like/', login_required(Like.as_view()), name="like"),
    path('follow/', login_required(Follow.as_view()), name="follow"),
    path('webhook/', AWSLambdaWebhook.as_view(), name="webhook"),
]

feed/models.py
from django.db.models import Model, ForeignKey, CASCADE, DateTimeField, TextField, CharField, ImageField
from django.contrib.auth import get_user_model


class Post(Model):
    user = ForeignKey(get_user_model(), on_delete=CASCADE)
    body = TextField(max_length=250)
    datetime_created = DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body


class Like(Model):
    user = ForeignKey(get_user_model(), on_delete=CASCADE)
    post = ForeignKey(Post, on_delete=CASCADE)
    datetime_created = DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')


class Tag(Model):
    tag = CharField(max_length=25, unique=True)

    def __str__(self):
        return self.tag


class PostTag(Model):
    post = ForeignKey(Post, on_delete=CASCADE)
    tag = ForeignKey(Tag, on_delete=CASCADE)
    datetime_created = DateTimeField(auto_now_add=True)


class Image(Model):
    image = ImageField(upload_to="images/")
    post = ForeignKey(Post, on_delete=CASCADE)


class AuthorFollower(Model):
    author = ForeignKey(get_user_model(), on_delete=CASCADE, related_name='author')
    follower = ForeignKey(get_user_model(), on_delete=CASCADE, related_name='follower')

    class Meta:
        unique_together = ('author', 'follower')

templates/ajax_likes.html
<!DOCTYPE html>
{% load custom_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <div class="instacard__likes-action">
        {% if user.is_authenticated %}
            <form action="{% url 'like' %}" method="post">
                {% csrf_token %}
                <button id="like_button" type="submit" name="post_id" value="{{ p.pk }}">
                    {% if user.pk in p.like_set.all|get_likes %}
                        <img src="{% static 'images/liked.png' %}">
                    {% else %}
                        <img src="{% static 'images/not_liked.png' %}">
                    {% endif %}
                </button>
            </form>
        {% else %}
            <img src="{% static 'images/not_liked.png' %}">
        {% endif %}
    </div>
    <div class="instacard__likes-counter">
        {% if p.like_set.all|length == 1 %}
            1 like
        {% else %}
            {{ p.like_set.all|length }} likes
        {% endif %}
    </div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Feed</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'bundle.js' %}"></script>

</head>
<body>

        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'feed' %}">Djangogramm</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                  {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'profile' user.pk %}">{{ user }}</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'create_post' %}">Create Post</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'login' %}">Sign In</a>
                    </li>
                  {% endif %}
              </ul>
            </div>
          </div>
        </nav>

    {% block content %}
    {% endblock %}

    {% block posts %}
    {% endblock %}

</body>
</html>

templates/base_posts.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block posts %}

<div class="posts-container">
    {% if page_obj|is_page and page_obj %}
        {% for p in page_obj %}
        <div class="instacard">
            <div class="instacard__header">
                <span class="instacard__header-avatar">
                    {% if user.is_authenticated and p.user.avatar %}
                        <img src="{{ p.user.avatar.url }}">
                    {% else %}
                        <img src="{% static 'images/avatar.png' %}">
                    {% endif %}
                </span>
                <span class="instacard__header-fullname">
                    {% if user.is_authenticated %}
                        <a href="{% url 'profile' p.user.pk %}">{{ p.user.first_name }} {{ p.user.last_name }}</a>
                    {% else %}
                        Author
                    {% endif %}
                </span>
            </div>

            <div id="carousel{{ p.user.pk }}{{ p.pk }}" class="carousel slide">
                <div class="carousel-inner">
                  {% for image in p.image_set.all %}
                    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                        <img src="{{ image.image.url }}" width="600" height="800">
                    </div>
                  {% endfor %}
                </div>

                {% if p.image_set.all|length != 1 %}
                    <div class="carousel-indicators">
                      {% for image in p.image_set.all %}
                        {% if forloop.counter0 == 0 %}
                            <button type="button" data-bs-target="#carousel{{ p.user.pk }}{{ p.pk }}"
                                    data-bs-slide-to="{{ forloop.counter0 }}" class="active" aria-current="true"
                                    aria-label="Slide {{ forloop.counter }}">
                            </button>
                        {% else %}
                            <button type="button" data-bs-target="#carousel{{ p.user.pk }}{{ p.pk }}"
                                    data-bs-slide-to="{{ forloop.counter0 }}" aria-label="Slide {{ forloop.counter }}">
                            </button>
                        {% endif %}
                      {% endfor %}
                    </div>

                    <button class="carousel-control-prev" type="button" data-bs-target="#carousel{{ p.user.pk }}{{ p.pk }}" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carousel{{ p.user.pk }}{{ p.pk }}" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                    </button>
                {% endif %}
            </div>

            <div class="instacard__likes_{{ p.pk }}">
                {% include 'ajax_likes.html' %}
            </div>

            <div class="instacard__body">
                {{ p.body }}
            </div>

            <div class="instacard__tags">
                <p>{{ p.posttag_set.all|get_tags }}</p>
            </div>

        </div>
        {% endfor %}

        <div class="pagin">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% else %}
        <div class="message-wrapper">
            No posts yet
        </div>
    {% endif %}
</div>

<script type="text/javascript">

    $(document).on('click', '#like_button', function(event){
        event.preventDefault();
        var post_id = $(this).attr('value');

        $.ajax({
            type: "POST",
            url: {% url 'like' %},
            data: {'post_id': post_id, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            success: function(response){
              $('.instacard__likes_'+post_id).html(response)
              console.log('Successful like request on post_id '+post_id);
            },
            error: function(rs, e){
                console.log(rs.responseText);
            },
        });
    });

</script>

{% endblock %}

templates/message.html
{% extends 'base.html' %}

{% block content %}
    <div class="message-wrapper">
        <p>{{ message }}</p>
    </div>

{% endblock %}